# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Nice to meet you
description: Jekyll microtheme that looks like JSON
baseurl: "/personal-page"
url: https://kautsarv.github.io

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  status: 200
  description:
    - Hi!
    - I'm Kautsar Virzawan
    - I'm a Software Tester
    - Currently working at
    - Allianz Indonesia
    - Let's connect
  cv: assets/cv.pdf
  address:
    city: jakarta
    country: indonesia
  email: ochank255@yahoo.com
  profiles:
    blog: https://kautsarv.github.io/starvedgeek/
    linkedin: https://www.linkedin.com/in/kautsar-virzawan/
    github: https://github.com/Kautsarv
    personal instagram: https://www.instagram.com/kautsarv/?hl=id
    food review instagram: https://www.instagram.com/starvedgeek/?hl=id

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
